version: "3.4"

networks: 
  nttdata-prueba:

services: 
  nttdata-ws-prueba-1.0.0:
    container_name: nttdata-ws-prueba-1.0.0
    image: 'nttdata-ws-prueba-1.0.0:lastest'
    build: ./apirest/
    ports: 
      - "8003:8003"
    networks: 
      - nttdata-prueba
    depends_on: 
      - db-postgres

  db-postgres:
    container_name: nttdata-db-postgres-api
    image: postgres
    networks:
      - nttdata-prueba
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=servicioDB